# Generated by Django 6.0.6 on 2026-06-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='ubicacion',
            field=models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], max_length=30),
        ),
    ]
